# Generated by Django 3.0 on 2019-12-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_titel', models.CharField(max_length=200)),
                ('post_tweet', models.CharField(max_length=200)),
            ],
        ),
    ]
